### ISSUE TITLE
relative abundance

### ISSUE THREAD

**Issue by ann-sophiek** [allind/EukDetect#11]
From your tool it’s possible to identify which eukaryotic species are present in a sample. Is it also possible to calculate the abundance of these species in one sample? Can I calculate this from the 'Marker_read_count column' or which file/column do I have to look at?

**Comment by allind** [comment]
There is currently no way to calculate relative abundance directly in eukdetect. You can get a sense for which eukaryotes are more prevalent by looking at the columns for percent observed markers (how many of the marker genes for a species are observed), and the total marker coverage (what amount of the observed markers are aligned by reads), but these aren't directly comparable across species because of difference in numbers of markers, gene size, and genome size in species. This is a feature that is being worked on, however.
